apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-stage-20
  namespace: stage
  labels:
    app: nginx-stage-20
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-stage
      version: "20"
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: nginx-stage
        version: "20"
    spec:
      containers:
      - name: nginx-stage-20
        image: nginx
        ports:
        - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-stage
  name: nginx-stage-svc
spec:
  ports:
  - name: port
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-stage
  type: NodePort
